Try to add a choice for Uefi bootloader, part 2

diff --git a/scripts/setup-nutyx.in b/scripts/setup-nutyx.in
--- a/scripts/setup-nutyx.in
+++ b/scripts/setup-nutyx.in
@@ -1648,7 +1648,7 @@ setup_install() {
 		[ ! -z $EFI_SYS_PART ] && FORMAT=`print_file_system $EFI_SYS_PART`
 		if [ "$FORMAT" == "vfat" ];then
 			dialog --title " $(gettext "Choose your favorite Boot Manager") " \
-				--menu "$(gettext "Grub, Efibootmgr or nothing"): $result" 20 60 3 \
+				--menu "$(gettext "Grub, Efibootmgr or nothing"): $result" 15 60 3 \
 			        "Grub" "$(gettext "Advanced Linux Kernel boot manager")" \
 			        "Efibootmgr" "$(gettext "Classic boot tool")" \
 				"Nothing" "$(gettext "To use the one used on other distro")" 2>$TMP/boot_choice
@@ -1658,7 +1658,7 @@ setup_install() {
 		                0|2)
 				        case $boot_choice in
 						Grub)
-				                        setup_grub;;
+				                        setup_grub "$MF";;
 						Efibootmgr)
 							setup_efibootmgr "/media/cdrom" "$MF";;
 						Nothing)
@@ -1721,6 +1721,210 @@ $(gettext "an simplify VI editor will allow you to modify it").\n\n \
 			vi $GRUB_CONFIG_DIR/$GRUB_CONFIG_FILE;;
 	esac
 }
+
+setup_grub_efi() {
+local SPNR OPTIONS
+        mount $PARTITION ${1}
+        OPTIONS=`cat /proc/cmdline|sed "s@BOOT_IMAGE=/boot/kernel\ @@"`
+        SPNR=`echo $PARTITION|sed "s@^/dev/[a-z]*@@"`
+        mount -t efivarfs efivarfs /sys/firmware/efi/efivars
+        mkdir -p ${1}/boot/efi
+        mount "$EFI_SYS_PART" ${1}/boot/efi
+        mkdir -p ${1}/boot/efi/EFI/BOOT/$SPNR
+        rm ${1}/boot/efi/EFI/BOOT/$SPNR/* 2>/dev/null
+
+local GRUB_CONFIG_FILE GRUB_CONFIG_DIR GRUB_DESTINATION_DIR GRUB_LOG_FILE
+        GRUB_CONFIG_FILE="grub.cfg"
+        GRUB_CONFIG_DIR=""
+        GRUB_DESTINATION_DIR=""
+        GRUB_LOG_FILE=$TMP/grub.log
+        if [ "$CHECK_HD_OK" == "no" ]; then
+                check_available_disk
+                [ "$CHECK_HD_OK" == "no" ] && return
+        fi
+        if [ "$CHECK_PART_OK" == "no" ]; then
+                check_available_partition
+                [ "$CHECK_PART_OK" == "no" ] && return
+        fi
+        if [ -z $DISK ]; then
+                select_disk "$(gettext "Configure the boot of the PC")"
+                [ "$DISK" == "no" ] && return
+        fi
+        if [ "$SETUP_INSTALL" != "yes" ]; then
+                [ "$CHECK_SINGLE_PARTITION" == "no" ] && unset PARTITION
+        fi
+        if [ -z $PARTITION ]; then
+                select_partition "$(gettext "Configure the boot of the PC")"
+                [ "$PARTITION" == "no" ] && return
+        fi
+        FORMAT=`print_file_system $PARTITION`
+        if [ "$FORMAT" == "no" ]; then
+                setup_format
+                [ "$FORMAT" == "no" ] && return
+        fi
+	mkdir $TMP/boot_partition
+        mount $PARTITION $TMP/boot_partition
+        echo "$PARTITION" > $TMP/boot_part
+        if [ -d $TMP/boot_partition/boot ]; then
+                # YaoLinuX is installed means we install GRUB after install
+                GRUB_DESTINATION_DIR="boot/"
+        fi
+        GRUB_CONFIG_DIR="$TMP/boot_partition/${GRUB_DESTINATION_DIR}grub"
+        mkdir $GRUB_CONFIG_DIR 2> /dev/null
+#       if [ -f $GRUB_CONFIG_DIR/MBR.original ]; then
+#               dialog --title " !!! Oups !!!! " \
+#               --msgbox " $(gettext "You already have a copy of the original MBR, I will not make a backup of it") " \
+#               6 50
+#       else
+#               cp $TMP/MBR $GRUB_CONFIG_DIR/MBR.original
+#               dialog --title " $(gettext "Good to know") " \
+#               --msgbox " $(gettext "A copy of the original MBR is saved in the folder /boot/grub of your YaoLinuX. It will then be possible to >
+#       fi
+        if [ ! -f $GRUB_CONFIG_DIR/$GRUB_CONFIG_FILE ]; then
+                cat > $GRUB_CONFIG_DIR/$GRUB_CONFIG_FILE << "EOF"
+# Begin grub.cfg
+# By default boot the first menu entry.
+set default=0
+# Allow 5 seconds before booting the default.
+set timeout=5
+
+insmod all_video
+if loadfont /boot/grub/fonts/unicode.pf2; then
+ set gfxmode=800x600
+ insmod efi_gop
+ insmod efi_uga
+ insmod video_bochs
+ insmod video_cirrus
+ insmod gfxterm
+ insmod png
+ terminal_output gfxterm
+fi
+
+if background_image /boot/grub/splash.png; then
+  set color_normal=light-gray/black
+  set color_highlight=white/black
+else
+  set color_normal=cyan/blue
+  set color_highlight=white/blue
+fi
+
+EOF
+        fi
+# Writing of NEW MBR
+        BOOT_FS="`print_file_system $PARTITION`"
+        LANG=C /sbin/grub-install --recheck --force --boot-directory=$TMP/boot_partition/${GRUB_DESTINATION_DIR} ${DISK} > ${GRUB_LOG_FILE} 2>&1
+        if ! (grep finished ${GRUB_LOG_FILE} > /dev/null); then
+                echo "/sbin/grub-install --recheck --force --boot-directory=$TMP/boot_partition/${GRUB_DESTINATION_DIR} [`echo $DISK`]" >> ${GRUB>
+                mount >> ${GRUB_LOG_FILE}
+                echo "DISK=${DISK}" >> ${GRUB_LOG_FILE}
+                echo "GRUB_DESTINATION_DIR=${GRUB_DESTINATION_DIR}" >> ${GRUB_LOG_FILE}
+                echo "GRUB_CONFIG_DIR=${GRUB_CONFIG_DIR}" >> ${GRUB_LOG_FILE}
+                echo "YaoLinuX_PART=${YaoLinuX_PART}" >> ${GRUB_LOG_FILE}
+                echo "BOOT_FS=${BOOT_FS}" >> ${GRUB_LOG_FILE}
+                echo "YaoLinuX_FS=${YaoLinuX_FS}" >> ${GRUB_LOG_FILE}
+                echo "PATH=$PATH" >> ${GRUB_LOG_FILE}
+                env >> ${GRUB_LOG_FILE}
+                # Restore MBR
+                #dd if=$TMP/MBR of=$DISK bs=512 count=1 > 2/dev/null
+                dialog --title " $(gettext "Something went wrong probably the file system is not supported") " \
+                --msgbox "`cat ${GRUB_LOG_FILE}`" 30 70
+                umount $TMP/boot_partition
+                umount /mnt/hd 2>/dev/null
+                error "Sorry, I cannot install GRUB" # die now
+        fi
+        if [ -f $TMP/boot ]; then
+                #
+                # The $TMP/boot file contains the YaoLinuX partition
+                #
+                YaoLinuX_PART="`cat $TMP/boot`"
+                BOOT_FS="`print_file_system $PARTITION`"
+                YaoLinuX_FS="`print_file_system $YaoLinuX_PART`"
+                echo "menuentry \"YaoLinuX LTS ${SETUP_ARCH} ${YaoLinuX_FS} on ${YaoLinuX_PART}\" {" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo " linux /${GRUB_DESTINATION_DIR}kernel-lts root=${YaoLinuX_PART} ro quiet verbose=no" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FI>
+                echo "#  initrd /${GRUB_DESTINATION_DIR}initrd-lts" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "}" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo " " >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "menuentry \"YaoLinuX LTS Verbose ${SETUP_ARCH} ${YaoLinuX_FS} on ${YaoLinuX_PART}\" {" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_>
+                echo "  linux /${GRUB_DESTINATION_DIR}kernel-lts root=${YaoLinuX_PART} ro " >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "#  initrd /${GRUB_DESTINATION_DIR}initrd-lts" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "}" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo " "  >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "menuentry \"YaoLinuX ${SETUP_ARCH} ${YaoLinuX_FS} on ${YaoLinuX_PART}\" {" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo " linux /${GRUB_DESTINATION_DIR}kernel root=${YaoLinuX_PART} ro quiet verbose=no" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "#  initrd /${GRUB_DESTINATION_DIR}initrd" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "}" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo " " >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "menuentry \"YaoLinuX Verbose ${SETUP_ARCH} ${YaoLinuX_FS} on ${YaoLinuX_PART}\" {" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "  linux /${GRUB_DESTINATION_DIR}kernel root=${YaoLinuX_PART} ro " >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "#  initrd /${GRUB_DESTINATION_DIR}initrd" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+                echo "}" >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}
+
+        else
+                #
+                # YaoLinuX is not yet installed
+                #
+		cat >> ${GRUB_CONFIG_DIR}/${GRUB_CONFIG_FILE}  << "EOF"
+#################################################################
+#                                                               #
+#               Example of a menuentry:                         #
+#                                                               #
+#   The YaoLinuX distribution to boot from is located:          #
+#      on the SECOND harddisk ( HDD 2 ) AND                     #
+#      the second harddisk has THREE partitions.                #
+#      YaoLinuX IS installed on the third partition.            #
+#                                                               #
+# NOTE:                                                         #
+# -----                                                         #
+#                                                               #
+#  ==>>>    Harddisk start AT ZERO                              #
+#  ==>>>    Partition start AT ONE                              #
+#                                                               #
+# We need to inform GRUB that we use the kernel on              #
+# the Partition Number 3 of Harddisk Number 2                   #
+#                                                               #
+#  ======>  set root=(hd1,3)                                    #
+#                                                               #
+# And we need to inform the kernel to look at the right place:  #
+#                                                               #
+#  ======>  root=/dev/sdb3                                      #
+#                                                               #
+#           Below the menuentry of this example:                #
+#       ( adjust to your needs and remove the '#' )             #
+#                                                               #
+#################################################################
+#
+#menuentry  "Harddisk number 2 and partition number 3" {
+#   set root=(hd1,3)
+#   linux /boot/kernel-lts root=/dev/sdb3 ro quiet verbose=no
+#}
+#
+# The same one for debug purpose:
+#
+#menuentry  "Harddisk number 2 and partition number 3 verbose mode" {
+#   set root=(hd1,3)
+#   linux /boot/kernel-lts root=/dev/sdb3 ro
+#}
+#
+# An other one with initrd and rootdelay (to use with USB stick for ex)
+#
+#menuentry  "Harddisk number 2 and partition number 1 with initrd" {
+#   set root=(hd1,1)
+#   linux /boot/kernel-lts root=/dev/sdb1 ro rootdelay=5
+#   initrd /boot/initrd-lts
+#}
+#
+EOF
+                if [ ! -f $TMP/boot_partition/${GRUB_DESTINATION_DIR}initrd ]; then
+                        cp /media/cdrom/boot/initrd \
+                        $TMP/boot_partition/${GRUB_DESTINATION_DIR}initrd 2> /dev/null
+                        cp /media/cdrom/boot/kernel \
+                        $TMP/boot_partition/${GRUB_DESTINATION_DIR}kernel 2> /dev/null
+                fi
+                MBR_ok
+        fi
+        umount $PARTITION
+}
+
 setup_grub() {
 	local GRUB_CONFIG_FILE GRUB_CONFIG_DIR GRUB_DESTINATION_DIR GRUB_LOG_FILE
 	GRUB_CONFIG_FILE="grub.cfg"
